export const destinations = [
  { name: "Nearby", description: "Find what's around you", icon: "✈️" },
  {
    name: "Pocono Mountains, PA",
    description: "Popular lake destination",
    icon: "🏔️",
  },
  {
    name: "Orlando, FL",
    description: "For sights like Walt Disney World Resort",
    icon: "🏰",
  },
  {
    name: "Paris, France",
    description: "For its bustling nightlife",
    icon: "🗼",
  },
  { name: "Miami, FL", description: "For its seaside allure", icon: "🏖️" },
  {
    name: "San Juan, Puerto Rico",
    description: "For its top-notch dining",
    icon: "🏝️",
  },
  {
    name: "New York, NY",
    description: "For sights like Central Park",
    icon: "🗽",
  },
  { name: "Los Angeles, CA", description: "For Hollywood glamour", icon: "🌴" },
  {
    name: "Tokyo, Japan",
    description: "For modern culture and cuisine",
    icon: "🏯",
  },
  { name: "London, UK", description: "For historic charm", icon: "🏰" },
];

export const properties = [
  {
    id: 1,
    title: "Home in San Juan",
    location: "San Juan, Puerto Rico",
    price: 137,
    rating: 4.9,
    reviews: 127,
    dates: "Feb 2 nights",
    image: "/placeholder.svg?height=300&width=400&text=San+Juan+Beach+House",
    isGuestFavorite: true,
    host: "Hosted by Maria",
  },
  {
    id: 2,
    title: "Apartment in Buckell Business District",
    location: "New York, NY",
    price: 278,
    rating: 4.85,
    reviews: 89,
    dates: "Feb 3 nights",
    image: "/placeholder.svg?height=300&width=400&text=NYC+Modern+Apartment",
    isGuestFavorite: false,
    host: "Hosted by John",
  },
  {
    id: 3,
    title: "Hotel in Buckell Business District",
    location: "Aspen, Colorado",
    price: 367,
    rating: 4.78,
    reviews: 156,
    dates: "Feb 3 nights",
    image: "/placeholder.svg?height=300&width=400&text=Aspen+Mountain+Hotel",
    isGuestFavorite: false,
    host: "Hosted by Sarah",
  },
  {
    id: 4,
    title: "Apartment in Buckell Business District",
    location: "Charleston, SC",
    price: 553,
    rating: 4.88,
    reviews: 203,
    dates: "Feb 3 nights",
    image:
      "/placeholder.svg?height=300&width=400&text=Charleston+Historic+Apartment",
    isGuestFavorite: false,
    host: "Hosted by Michael",
  },
  {
    id: 5,
    title: "Beachfront Villa with Pool",
    location: "Malibu, California",
    price: 892,
    rating: 4.95,
    reviews: 67,
    dates: "Mar 5 nights",
    image: "/placeholder.svg?height=300&width=400&text=Malibu+Beach+Villa",
    isGuestFavorite: true,
    host: "Hosted by Jennifer",
  },
  {
    id: 6,
    title: "Cozy Cabin in the Woods",
    location: "Big Sur, California",
    price: 245,
    rating: 4.92,
    reviews: 134,
    dates: "Mar 2 nights",
    image: "/placeholder.svg?height=300&width=400&text=Big+Sur+Cabin",
    isGuestFavorite: false,
    host: "Hosted by David",
  },
  {
    id: 7,
    title: "Modern Loft in Arts District",
    location: "Los Angeles, CA",
    price: 189,
    rating: 4.76,
    reviews: 98,
    dates: "Apr 4 nights",
    image: "/placeholder.svg?height=300&width=400&text=LA+Arts+District+Loft",
    isGuestFavorite: false,
    host: "Hosted by Alex",
  },
  {
    id: 8,
    title: "Luxury Penthouse with City Views",
    location: "Miami, Florida",
    price: 675,
    rating: 4.89,
    reviews: 145,
    dates: "Apr 3 nights",
    image: "/placeholder.svg?height=300&width=400&text=Miami+Penthouse",
    isGuestFavorite: true,
    host: "Hosted by Carlos",
  },
  {
    id: 9,
    title: "Historic Brownstone",
    location: "Boston, Massachusetts",
    price: 298,
    rating: 4.83,
    reviews: 176,
    dates: "May 2 nights",
    image: "/placeholder.svg?height=300&width=400&text=Boston+Brownstone",
    isGuestFavorite: false,
    host: "Hosted by Emily",
  },
  {
    id: 10,
    title: "Desert Oasis Retreat",
    location: "Scottsdale, Arizona",
    price: 423,
    rating: 4.91,
    reviews: 87,
    dates: "May 4 nights",
    image:
      "/placeholder.svg?height=300&width=400&text=Scottsdale+Desert+Retreat",
    isGuestFavorite: false,
    host: "Hosted by Robert",
  },
  {
    id: 11,
    title: "Lakefront Cottage",
    location: "Lake Tahoe, California",
    price: 356,
    rating: 4.94,
    reviews: 112,
    dates: "Jun 3 nights",
    image: "/placeholder.svg?height=300&width=400&text=Lake+Tahoe+Cottage",
    isGuestFavorite: true,
    host: "Hosted by Lisa",
  },
  {
    id: 12,
    title: "Urban Studio in Downtown",
    location: "Seattle, Washington",
    price: 167,
    rating: 4.72,
    reviews: 234,
    dates: "Jun 2 nights",
    image: "/placeholder.svg?height=300&width=400&text=Seattle+Downtown+Studio",
    isGuestFavorite: false,
    host: "Hosted by Mark",
  },
];

export const inspirationCategories = [
  "Popular",
  "Arts & culture",
  "Beach",
  "Mountains",
  "Outdoors",
  "Things to do",
  "Unique stays",
  "Travel tips & inspiration",
  "Airbnb-friendly apartments",
];

export const inspirationDestinations = [
  { name: "Amsterdam", type: "Cottage rentals", distance: "4,234 miles away" },
  { name: "Memphis", type: "Condo rentals", distance: "1,045 miles away" },
  { name: "Charlotte", type: "Cabin rentals", distance: "567 miles away" },
  { name: "Dallas", type: "Monthly Rentals", distance: "1,234 miles away" },
  { name: "Detroit", type: "Monthly Rentals", distance: "876 miles away" },
  {
    name: "Albuquerque",
    type: "Monthly Rentals",
    distance: "1,567 miles away",
  },
  { name: "Gulf Shores", type: "Condo rentals", distance: "789 miles away" },
  {
    name: "Niagara Falls",
    type: "Vacation rentals",
    distance: "1,123 miles away",
  },
  {
    name: "North Myrtle Beach",
    type: "Vacation rentals",
    distance: "645 miles away",
  },
  { name: "Portland", type: "Vacation rentals", distance: "2,345 miles away" },
  { name: "Nice", type: "Villa rentals", distance: "5,678 miles away" },
  { name: "Brooklyn", type: "Monthly Rentals", distance: "234 miles away" },
  {
    name: "Barcelona",
    type: "Apartment rentals",
    distance: "4,567 miles away",
  },
  { name: "Tokyo", type: "City stays", distance: "6,789 miles away" },
  { name: "Rome", type: "Historic rentals", distance: "4,890 miles away" },
  { name: "Sydney", type: "Beach rentals", distance: "8,765 miles away" },
  { name: "London", type: "City apartments", distance: "3,456 miles away" },
  { name: "Dubai", type: "Luxury stays", distance: "7,234 miles away" },
];
